In [47]:
#imports
import pandas as pd
import matplotlib.pyplot as plt

#look at data
sales_data = pd.read_csv('data/supermarket_sales.csv')
sales_data.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales'],
      dtype='object')

In [48]:
sales_data.describe()

            Row ID   Postal Code         Sales
count  9800.000000   9789.000000   9800.000000
mean   4900.500000  55273.322403    230.769059
std    2829.160653  32041.223413    626.651875
min       1.000000   1040.000000      0.444000
25%    2450.750000  23223.000000     17.248000
50%    4900.500000  58103.000000     54.490000
75%    7350.250000  90008.000000    210.605000
max    9800.000000  99301.000000  22638.480000

In [49]:
#time to clean
sales_data = sales_data.dropna()
sales_data.shape[0]
sales_data['Order Date'] = pd.to_datetime(sales_data['Order Date'], format='%d/%m/%Y')
sales_data['Ship Date'] = pd.to_datetime(sales_data['Ship Date'], format='%d/%m/%Y')
sales_data.dtypes

Row ID                    int64
Order ID                 object
Order Date       datetime64[ns]
Ship Date        datetime64[ns]
Ship Mode                object
Customer ID              object
Customer Name            object
Segment                  object
Country                  object
City                     object
State                    object
Postal Code             float64
Region                   object
Product ID               object
Category                 object
Sub-Category             object
Product Name             object
Sales                   float64
dtype: object

Getting some numbers together!

In [50]:
print(f"In total we have received {sales_data['Order ID'].count()} orders.")
print(f"In total we have made sales worth €{sales_data['Sales'].sum():.2f}.")
print(f"In total we have {len(set(sales_data['Customer ID']))} customers.")

In total we have received 9789 orders.
In total we have made sales worth €2252607.41.
In total we have 793 customers.

In [ ]:
# monthly sales
monthly_sales = sales_data.groupby([sales_data['Order Date'].dt.year.rename('Year'), 
                   sales_data['Order Date'].dt.month.rename('Month')])['Sales'].sum()

monthly_sales = monthly_sales.reset_index()
monthly_sales.columns = ['Year', 'Month', 'Total Sales']
monthly_sales['Month'] = monthly_sales['Month'].map({1:"January", 
                                            2: "February",
                                            3: "March",
                                            4: "April",
                                            5: "May",
                                            6: "June",
                                            7: "July",
                                            8: "August",
                                            9: "September",
                                            10: "October",
                                            11: "November",
                                            12: "December"})
monthly_sales

    Year      Month  Total Sales
0   2015    January   14205.7070
1   2015   February    4519.8920
2   2015      March   55205.7970
3   2015      April   27906.8550
4   2015        May   23644.3030
5   2015       June   34322.9356
6   2015       July   33781.5430
7   2015     August   27117.5365
8   2015  September   81623.5268
9   2015    October   31453.3930
10  2015   November   77907.6607
11  2015   December   68167.0585
12  2016    January   18066.9576
13  2016   February   11951.4110
14  2016      March   32339.3184
15  2016      April   34154.4685
16  2016        May   29959.5305
17  2016       June   23599.3740
18  2016       July   28608.2590
19  2016     August   36818.3422
20  2016  September   63133.6060
21  2016    October   31011.7375
22  2016   November   70129.2995
23  2016   December   74543.6012
24  2017    January   16870.1810
25  2017   February   22978.8150
26  2017      March   51165.0590
27  2017      April   37385.0170
28  2017        May   56656.9080
29  2017       June   39724.4860
30  2017       July   38320.7830
31  2017     August   30542.2003
32  2017  September   69193.3909
33  2017    October   59583.0330
34  2017   November   79066.4958
35  2017   December   95739.1210
36  2018    January   42839.2940
37  2018   February   19920.9974
38  2018      March   58863.4128
39  2018      April   35541.9101
40  2018        May   43825.9822
41  2018       June   48190.7277
42  2018       July   44825.1040
43  2018     August   62837.8480
44  2018  September   86152.8880
45  2018    October   77448.1312
46  2018   November  117938.1550
47  2018   December   82825.3588

In [ ]:
# Plotting to see trends

date = monthly_sales[]

plt.bar(monthly_sales['Total Sales'], 
               monthly_sales[], width=0.8, bottom=None, *, align='center', data=None, **kwargs)

SyntaxError: invalid syntax (16885758.py, line 3)

In [ ]:
# year-to-year growth rate 
yearly_sales = sales_data